### ISSUE TITLE
Camera2api

### ISSUE THREAD

**Issue by KirChi123** [MDNSSKNGHT/madness-camera-6.2.030#6]
How can I enable camera2api on Galaxy A20e and is there any way I can do it without root because I am afraid of bricking the device

**Comment by MDNSSKNGHT** [comment]
No, you'll need root, and you do have Camera2API, every phone shipped with Android Lollipop or above has, you may not have RAW Support, that's two different things. (Sorry for the late reply, really!)

**Comment by KirChi123** [comment]
Yes i meant raw support how to add it without root? Is there any way?

**Comment by MDNSSKNGHT** [comment]
You need to be root and a custom rom to install the app, reach me as MadnessKnight in telegram we'll discuss this deeper the, closing issue for now.
